source 'https://rubygems.org'
ruby '2.0.0'

gem 'ProMotion', '~> 1.0.4'
gem 'teacup'
gem 'bubble-wrap'
gem 'motion-cocoapods', '~> 1.4.0'
# gem 'formotion'
gem 'motion-testflight'
gem 'sugarcube', require: 'sugarcube-nsdate'
